# Generated by Django 3.2.12 on 2022-03-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_is_activ_prods_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(upload_to='products_images', verbose_name='изображение'),
        ),
    ]
