# Generated by Django 3.2.12 on 2022-03-01 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('mainapp', '0003_auto_20220226_1429'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_ad', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
