# Generated by Django 3.2.12 on 2022-03-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('basketapp', '0001_basket_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
    ]
